https://blog.gofynd.com/building-a-deep-q-network-in-pytorch-fa1086aa5435

In [ ]:
# ! apt-get install -y python-opengl
# ! apt-get install -y xvfb

In [ ]:
# ! pip install pyglet

In [ ]:
# !pip install gym

In [2]:
import torch
import torch.nn as nn
from torch import randint
import gym
import copy
from collections import deque
import random
from tqdm.notebook import tqdm

In [3]:
rew_arr = []
episode_count = 100
env = gym.make('CartPole-v0')
for i in range(episode_count):
    obs, done, rew = env.reset(), False, 0
    while (done != True) :
        A =  randint(0,env.action_space.n,(1,))
        obs, reward, done, info = env.step(A.item())
        print(obs, reward, done, info )
        rew += reward
    rew_arr.append(rew)
    
print("average reward per episode :",sum(rew_arr)/ len(rew_arr))

[ 0.03713844  0.16232584 -0.01318765 -0.2778378 ] 1.0 False {}
[ 0.04038495  0.35763344 -0.01874441 -0.57465076] 1.0 False {}
[ 0.04753762  0.16277921 -0.03023743 -0.28793132] 1.0 False {}
[ 0.0507932  -0.03189878 -0.03599605 -0.00493626] 1.0 False {}
[ 0.05015523  0.16372041 -0.03609478 -0.30875555] 1.0 False {}
[ 0.05342964  0.35933757 -0.04226989 -0.61259973] 1.0 False {}
[ 0.06061639  0.16483106 -0.05452188 -0.3335242 ] 1.0 False {}
[ 0.06391301 -0.02947421 -0.06119237 -0.05852088] 1.0 False {}
[ 0.06332353 -0.22366783 -0.06236278  0.21424502] 1.0 False {}
[ 0.05885017 -0.41784534 -0.05807788  0.4866223 ] 1.0 False {}
[ 0.05049326 -0.22195403 -0.04834544  0.17621547] 1.0 False {}
[ 0.04605418 -0.02617473 -0.04482113 -0.13131838] 1.0 False {}
[ 0.04553069  0.16955966 -0.0474475  -0.43779808] 1.0 False {}
[ 0.04892188 -0.02485972 -0.05620346 -0.16044156] 1.0 False {}
[ 0.04842469 -0.21913388 -0.05941229  0.11399442] 1.0 False {}
[ 0.04404201 -0.02321317 -0.0571324  -0.19682506] 1.0 F

[ 0.03706674  0.35885367 -0.18337215 -0.8894759 ] 1.0 False {}
[ 0.04424381  0.5559267  -0.20116167 -1.2337391 ] 1.0 False {}
[ 0.05536234  0.75298405 -0.22583646 -1.5821081 ] 1.0 True {}
[ 0.03237383  0.23808874  0.04404733 -0.2365474 ] 1.0 False {}
[0.0371356  0.04236608 0.03931638 0.06969758] 1.0 False {}
[ 0.03798293 -0.15329684  0.04071033  0.3745212 ] 1.0 False {}
[ 0.03491699 -0.3489727   0.04820076  0.6797573 ] 1.0 False {}
[ 0.02793754 -0.5447299   0.0617959   0.9872176 ] 1.0 False {}
[ 0.01704294 -0.74062246  0.08154026  1.2986519 ] 1.0 False {}
[ 0.00223049 -0.5466249   0.10751329  1.0325688 ] 1.0 False {}
[-0.00870201 -0.7429998   0.12816466  1.3569784 ] 1.0 False {}
[-0.023562   -0.5496973   0.15530424  1.1069802 ] 1.0 False {}
[-0.03455595 -0.35691956  0.17744383  0.8667699 ] 1.0 False {}
[-0.04169434 -0.55395466  0.19477923  1.209577  ] 1.0 False {}
[-0.05277343 -0.7509836   0.21897078  1.5564355 ] 1.0 True {}
[-0.04328362  0.15922481  0.04445639 -0.26282644] 1.0 False {

[-0.14321819 -0.05015204  0.21662457  0.56021494] 1.0 True {}
[ 0.01752159 -0.18381295 -0.03584134  0.250977  ] 1.0 False {}
[ 0.01384533  0.011802   -0.0308218  -0.05279207] 1.0 False {}
[ 0.01408137 -0.18286476 -0.03187764  0.2300092 ] 1.0 False {}
[ 0.01042408 -0.377517   -0.02727746  0.5124688 ] 1.0 False {}
[ 0.00287374 -0.1820217  -0.01702808  0.21131635] 1.0 False {}
[-0.00076669 -0.3768961  -0.01280176  0.49857953] 1.0 False {}
[-0.00830462 -0.5718352  -0.00283016  0.7872007 ] 1.0 False {}
[-0.01974132 -0.37667453  0.01291385  0.4936287 ] 1.0 False {}
[-0.02727481 -0.5719762   0.02278642  0.79035336] 1.0 False {}
[-0.03871434 -0.76740354  0.03859349  1.0901169 ] 1.0 False {}
[-0.05406241 -0.572811    0.06039583  0.80978906] 1.0 False {}
[-0.06551863 -0.37856627  0.07659161  0.5366988 ] 1.0 False {}
[-0.07308995 -0.18460004  0.08732559  0.2690984 ] 1.0 False {}
[-0.07678195  0.00917421  0.09270755  0.00518569] 1.0 False {}
[-0.07659847 -0.18714659  0.09281127  0.3256193 ] 1.0 Fa

[ 0.08284992  0.36888617 -0.10738897 -0.7215206 ] 1.0 False {}
[ 0.09022764  0.17540072 -0.12181938 -0.46447602] 1.0 False {}
[ 0.09373566 -0.01780821 -0.1311089  -0.21253675] 1.0 False {}
[ 0.0933795   0.17892078 -0.13535963 -0.54353327] 1.0 False {}
[ 0.09695791  0.37565932 -0.1462303  -0.875616  ] 1.0 False {}
[ 0.10447109  0.57243395 -0.16374262 -1.2104665 ] 1.0 False {}
[ 0.11591978  0.37976018 -0.18795195 -0.9732471 ] 1.0 False {}
[ 0.12351498  0.18758893 -0.20741689 -0.7449998 ] 1.0 False {}
[ 0.12726676 -0.00415944 -0.22231689 -0.5240864 ] 1.0 True {}
[ 0.0090099  -0.22585805 -0.02919215  0.3141685 ] 1.0 False {}
[ 0.00449274 -0.42055225 -0.02290878  0.59750414] 1.0 False {}
[-0.00391831 -0.61534625 -0.01095869  0.8828839 ] 1.0 False {}
[-0.01622523 -0.8103177   0.00669898  1.1721017 ] 1.0 False {}
[-0.03243158 -1.0055261   0.03014102  1.4668772 ] 1.0 False {}
[-0.05254211 -0.81078583  0.05947856  1.1837596 ] 1.0 False {}
[-0.06875782 -0.61648387  0.08315375  0.9102984 ] 1.0 Fa

[-0.02329227  0.23004875 -0.04866198 -0.27213055] 1.0 False {}
[-0.0186913   0.42583007 -0.05410459 -0.57975584] 1.0 False {}
[-0.0101747  0.6216668 -0.0656997 -0.8889801] 1.0 False {}
[ 0.00225864  0.81761587 -0.08347931 -1.2015713 ] 1.0 False {}
[ 0.01861096  1.0137123  -0.10751074 -1.519206  ] 1.0 False {}
[ 0.0388852   1.2099572  -0.13789485 -1.8434213 ] 1.0 False {}
[ 0.06308435  1.4063047  -0.17476328 -2.1755595 ] 1.0 False {}
[ 0.09121044  1.2132626  -0.21827447 -1.9415262 ] 1.0 True {}
[ 0.03117164 -0.15107095 -0.00675285  0.25985193] 1.0 False {}
[ 0.02815022 -0.34609586 -0.00155581  0.5503973 ] 1.0 False {}
[ 0.02122831 -0.15095209  0.00945214  0.2572246 ] 1.0 False {}
[ 0.01820927 -0.3462077   0.01459663  0.55287385] 1.0 False {}
[ 0.01128511 -0.54153156  0.02565411  0.85011965] 1.0 False {}
[ 4.5447974e-04 -7.3699379e-01  4.2656500e-02  1.1507580e+00] 1.0 False {}
[-0.0142854  -0.54245365  0.06567166  0.8717504 ] 1.0 False {}
[-0.02513447 -0.7384043   0.08310667  1.1843364 

[-0.48651686 -1.934658    0.21889731  2.178277  ] 1.0 True {}
[ 0.03845569 -0.22160837  0.03353199  0.3097516 ] 1.0 False {}
[ 0.03402353 -0.41719165  0.03972702  0.6128181 ] 1.0 False {}
[ 0.02567969 -0.22264674  0.05198338  0.3329077 ] 1.0 False {}
[ 0.02122676 -0.02830174  0.05864154  0.05706023] 1.0 False {}
[ 0.02066072 -0.22421335  0.05978274  0.36765322] 1.0 False {}
[ 0.01617646 -0.42013156  0.0671358   0.6785712 ] 1.0 False {}
[ 0.00777383 -0.6161188   0.08070723  0.9916129 ] 1.0 False {}
[-0.00454855 -0.42216417  0.10053949  0.7253302 ] 1.0 False {}
[-0.01299183 -0.61852205  0.11504609  1.0478884 ] 1.0 False {}
[-0.02536228 -0.81496704  0.13600387  1.374357  ] 1.0 False {}
[-0.04166162 -1.0115013   0.163491    1.7062981 ] 1.0 False {}
[-0.06189164 -1.208083    0.19761696  2.0450912 ] 1.0 False {}
[-0.0860533  -1.4046104   0.23851879  2.3918667 ] 1.0 True {}
[-0.01169819 -0.19106516  0.0368598   0.31226346] 1.0 False {}
[-0.0155195  -0.38669232  0.04310507  0.6163392 ] 1.0 Fal

In [4]:
class DQN_Agent:
    
    def __init__(self, seed, layer_sizes, lr, sync_freq, exp_replay_size):
        torch.manual_seed(seed)
        self.q_net = self.build_nn(layer_sizes)
        self.target_net = copy.deepcopy(self.q_net)
        self.q_net.cuda()
        self.target_net.cuda()
        self.loss_fn = torch.nn.MSELoss()
        self.optimizer = torch.optim.Adam(self.q_net.parameters(), lr=lr)
        
        self.network_sync_freq = sync_freq
        self.network_sync_counter = 0
        self.gamma = torch.tensor(0.95).float().cuda()
        self.experience_replay = deque(maxlen = exp_replay_size)  
        return
        
    def build_nn(self, layer_sizes):
        assert len(layer_sizes) > 1
        layers = []
        for index in range(len(layer_sizes)-1):
            linear = nn.Linear(layer_sizes[index], layer_sizes[index+1])
            act =    nn.Tanh() if index < len(layer_sizes)-2 else nn.Identity()
            layers += (linear,act)
        return nn.Sequential(*layers)
    
    def get_action(self, state, action_space_len, epsilon):
        # We do not require gradient at this point, because this function will be used either
        # during experience collection or during inference
        with torch.no_grad():
            Qp = self.q_net(torch.from_numpy(state).float().cuda())
        Q,A = torch.max(Qp, axis=0)
        A = A if torch.rand(1,).item() > epsilon else torch.randint(0,action_space_len,(1,))
        return A
    
    def get_q_next(self, state):
        with torch.no_grad():
            qp = self.target_net(state)
        q,_ = torch.max(qp, axis=1)    
        return q
    
    def collect_experience(self, experience):
        self.experience_replay.append(experience)
        return
    
    def sample_from_experience(self, sample_size):
        if(len(self.experience_replay) < sample_size):
            sample_size = len(self.experience_replay)   
        sample = random.sample(self.experience_replay, sample_size)
        s = torch.tensor([exp[0] for exp in sample]).float()
        a = torch.tensor([exp[1] for exp in sample]).float()
        rn = torch.tensor([exp[2] for exp in sample]).float()
        sn = torch.tensor([exp[3] for exp in sample]).float()   
        return s, a, rn, sn
    
    def train(self, batch_size ):
        s, a, rn, sn = self.sample_from_experience( sample_size = batch_size)
        if(self.network_sync_counter == self.network_sync_freq):
            self.target_net.load_state_dict(self.q_net.state_dict())
            self.network_sync_counter = 0
        
        # predict expected return of current state using main network
        qp = self.q_net(s.cuda())
        pred_return, _ = torch.max(qp, axis=1)
        
        # get target return using target network
        q_next = self.get_q_next(sn.cuda())
        target_return = rn.cuda() + self.gamma * q_next
        
        loss = self.loss_fn(pred_return, target_return)
        self.optimizer.zero_grad()
        loss.backward(retain_graph=True)
        self.optimizer.step()
        
        self.network_sync_counter += 1       
        return loss.item()

In [5]:
env = gym.make('CartPole-v0')
input_dim = env.observation_space.shape[0]
output_dim = env.action_space.n
exp_replay_size = 256
agent = DQN_Agent(seed=1423,
                  layer_sizes=[input_dim, 64, output_dim],
                  lr=1e-3,
                  sync_freq=5,
                  exp_replay_size=exp_replay_size)

In [6]:
# initiliaze experiance replay      
index = 0
for i in range(exp_replay_size):
    obs = env.reset()
    done = False
    while(done != True):
        A = agent.get_action(obs, env.action_space.n, epsilon=1)
        obs_next, reward, done, _ = env.step(A.item())
        agent.collect_experience([obs, A.item(), reward, obs_next])
        obs = obs_next
        index += 1
        if( index > exp_replay_size ):
            break
            

In [7]:
len(agent.experience_replay)

256

In [8]:
# Main training loop
losses_list, reward_list, episode_len_list, epsilon_list  = [], [], [], []
index = 128
episodes = 10000
epsilon = 1

for i in tqdm(range(episodes)):
    obs, done, losses, ep_len, rew = env.reset(), False, 0, 0, 0
    while(done != True):
        ep_len += 1 
        A = agent.get_action(obs, env.action_space.n, epsilon)
        obs_next, reward, done, _ = env.step(A.item())
        agent.collect_experience([obs, A.item(), reward, obs_next])
       
        obs = obs_next
        rew  += reward
        index += 1
        
        if(index > 128):
            index = 0
            for j in range(4):
                loss = agent.train(batch_size=16)
                losses += loss      
    if epsilon > 0.05 :
        epsilon -= (1 / 5000)
    
    losses_list.append(losses/ep_len), reward_list.append(rew), episode_len_list.append(ep_len), epsilon_list.append(epsilon)

In [10]:
from IPython import display
from xvfbwrapper import Xvfb
import numpy as np
import time
import pyglet
import gym
import PIL.Image
import io

vdisplay = Xvfb(width=1280, height=740)
vdisplay.start()

env = gym.make('CartPole-v0')
obs, done, rew = env.reset(), False, 0


def showarray(a, fmt='png'):
    a = np.uint8(a)
    f = io.BytesIO()
    ima = PIL.Image.fromarray(a).save(f, fmt)
    return f.getvalue()


imagehandle = display.display(display.Image(data=showarray(
    env.render(mode='rgb_array')),
                                            width=450),
                              display_id='gymscr')


while (done != True) :
    time.sleep(0.01)
    A =  agent.get_action(obs, env.action_space.n, epsilon = 0)
    obs, reward, done, info = env.step(A.item())
    rew += reward
    display.update_display(display.Image(data=showarray(
        env.render(mode='rgb_array')),
                                         width=450),
                           display_id='gymscr')

vdisplay.stop()

GLException: No GL context; create a Window first

In [ ]:
# env = gym.make('CartPole-v0')
# env = gym.wrappers.Monitor(env, "record_dir")
# for i in tqdm(range(2)):
#     obs, done, rew = env.reset(), False, 0
#     while (done != True) :
#         A =  agent.get_action(obs, env.action_space.n, epsilon = 0)
#         obs, reward, done, info = env.step(A.item())
#         rew += reward
#         sleep(0.01)
#         env.render()  
#     print("episode : {}, reward : {}".format(i,rew)) 

In [ ]:
# !pip install xvfbwrapper

In [ ]:
from IPython import display
from xvfbwrapper import Xvfb
import numpy as np
import time
import pyglet
import gym
import PIL.Image
import io    

vdisplay = Xvfb(width=1280, height=740)
vdisplay.start()

env = gym.make('CartPole-v0')
env.reset()

def showarray(a, fmt='png'):
    a = np.uint8(a)
    f = io.BytesIO()
    ima = PIL.Image.fromarray(a).save(f, fmt)
    return f.getvalue()

imagehandle = display.display(display.Image(data=showarray(env.render(mode='rgb_array')), width=450), display_id='gymscr')


for _ in range(2):
  time.sleep(0.01)
  observation, reward, done, info = env.step(env.action_space.sample()) # take a random action
  display.update_display(display.Image(data=showarray(env.render(mode='rgb_array')), width=450), display_id='gymscr')


vdisplay.stop()